### ISSUE TITLE
Update N3-Bower

### ISSUE THREAD

**Issue by jvdzwaan** [RubenVerborgh/N3-Bower#1]
I would really like to use N3-bower to parse trig files, however, it seems that the current version does not yet include trig parsing. Would you mind updating this repository to the newest version of N3?

**Comment by RubenVerborgh** [comment]
Hey @jvdzwaan, will do! Should have an automated build process for this… :smile:

**Comment by jvdzwaan** [comment]
Thanks!
An automated build script would be even better :)

**Comment by RubenVerborgh** [comment]
Here you do: https://github.com/RubenVerborgh/N3-Bower/tree/v0.4.3
